version: "2"
services:
  web:
    container_name: bepal-ws
    build: .
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: bepal-ws_mongo
    image: mongo
    ports:
      - '27017:27017'